### PR TITLE
21 webapp fixing

### PR DESCRIPTION
**Pull request by inigo99**
Hey Crypto-Fam! Here's all the fixes needed for the web app to run correctly. I've checked them and the api runs correctly with all the endpoints. Check it plz. <3

### CODE REVIEW

**Comment by ianrecke** [comment]
all works properly!

**Review by ianrecke — COMMENTED** [review]
All good!

**Review by iNigoh — APPROVED** [review]
Great idea creating the ParametersCheck class!! 😄

**Comment by inigo99** [comment]
YEET!

**Pull request merged**
